/* Contenido ampliado 13: vida adulta y muchos tips más. */
'use strict';
const S14 = (id, titulo, pasa, hacer, sale, practica, extra) => ({ id, titulo, pasa, hacer, ejemplos: [], cierre: '', extra: extra || [], sale, practica });

GUIA.push(
  { bloque:'Vida adulta y círculo social', items:[
    S14('g-amigos-se-van', 'Tus amigos se van de la ciudad o cambian de vida', 'Cada vez hay menos gente con quien quedar.', [
      'Es normal a tu edad. Los grupos cambian, y no es culpa tuya.',
      'Mantén el contacto con los que más te importan: un mensaje, una llamada, un plan al mes.',
      'Busca gente nueva con actividades que te gusten.',
      'Cuida a los amigos que siguen: dedícales tiempo.'
    ], 'La vida social se reconstruye con pequeños planes.', 'Proponer un plan a un amigo esta semana'),
    S14('g-ciudad-solo', 'Te sientes solo en una ciudad grande', 'Barcelona está llena de gente y aun así te sientes solo.', [
      'Es muy común. La soledad no es falta de gente, es falta de conexión.',
      'Apúntate a algo semanal: así ves las mismas caras y se crean vínculos.',
      'Un café con alguien de vez en cuando vale más que mil likes.',
      'Si el vacío es muy grande, habla con tu psicóloga.'
    ], 'La conexión se construye poco a poco.', 'Apuntarme a una actividad semanal'),
    S14('g-cena-familiar', 'Una cena familiar con preguntas incómodas', 'Te preguntan por pareja, trabajo y planes.', [
      'Prepara una frase tranquila: «Estoy bien así, todo va a su ritmo».',
      'Cambia de tema con una pregunta a quien te pregunta.',
      'Si te agobia, sal un momento a respirar.',
      'Recuerda que lo hacen con cariño, aunque duela.'
    ], 'Tu vida es tuya y va a tu ritmo.', 'Preparar una respuesta amable y cerrada'),
    S14('g-bodas-solo', 'Ir solo a una boda o un evento de amigos con pareja', 'Todos van en pareja y tú solo.', [
      'No pasa nada: mucha gente va sola. Es una buena ocasión para conocer a más.',
      'Habla con todo el mundo: la gente se alegra de que alguien socialice.',
      'Baila, brinda y disfruta sin pensar en lo que falta.',
      'Si te sientes mal, apártate un rato y vuelve.'
    ], 'Ir solo a una boda es mucho más fácil de lo que parece.', 'Ir a un evento y hablar con tres personas'),
    S14('g-organizar', 'Organizar un plan tú', 'Siempre esperas a que otros propongan.', [
      'Empieza por algo pequeño: unas cañas, un vermut o una cena sencilla.',
      'Invita a 3-5 personas y deja claro día, hora y sitio.',
      'No te agobies si alguien falla: pasa a todos.',
      'Cada vez será más fácil y tu círculo crecerá.'
    ], 'Quien organiza, conoce más gente.', 'Organizar un plan pequeño este mes'),
    S14('g-hobby', 'Empezar un hobby nuevo', 'Quieres probar algo pero no sabes por dónde.', [
      'Elige algo que te dé curiosidad, no lo que «deberías».',
      'Apúntate a una prueba gratuita o a una clase suelta.',
      'Ve tres veces antes de decidir si te gusta.',
      'Los hobbies en grupo suman amigos y temas de conversación.'
    ], 'Un hobby nuevo te da algo que contar y gente nueva.', 'Probar una clase de algo que no he hecho nunca'),
    S14('g-movil', 'Pasas demasiado tiempo con el móvil', 'Sientes que el móvil te roba tiempo y ánimo.', [
      'Ponte límites sencillos: sin móvil en la comida, lejos de la cama.',
      'Silencia las notificaciones que no necesitas.',
      'Reemplaza el rato de móvil por algo: andar, leer, música.',
      'Mirar menos redes suele mejorar el ánimo y la autoestima.'
    ], 'Pequeños cambios traen grandes mejoras.', 'Dejar el móvil fuera del dormitorio'),
    S14('g-rutina', 'Rutina sin sentido', 'Los días se parecen y sientes que no avanzas.', [
      'Añade una cosa nueva por semana: un plan, una ruta, una comida.',
      'Marca un pequeño objetivo semanal que te ilusione.',
      'Mira atrás: seguro que has avanzado más de lo que crees.',
      'Habla de ello en terapia o con alguien de confianza.'
    ], 'Cambiar poco a poco funciona mejor que cambiar todo de golpe.', 'Hacer una cosa distinta esta semana'),
    S14('g-vacaciones', 'Vacaciones sin plan', 'Se acercan y no tienes con quién ir.', [
      'Plantéate un viaje corto a un sitio que te apetezca. Viajar solo es una gran experiencia.',
      'Alójate en sitios con ambiente social (albergues, tours) si quieres conocer gente.',
      'Propón a amigos con tiempo y concreta fechas.',
      'No esperes a que alguien lo organice por ti.'
    ], 'Cada viaje te hace más seguro.', 'Mirar un destino cercano que me apetezca')
  ]}
);

TIPS.push(
  ['Mirada', 'Mirar a los ojos mientras escuchas muestra interés. Mirar a los ojos mientras hablas muestra seguridad.'],
  ['Mirada', 'Si la mirada se te escapa por los nervios, mira entre las cejas o la nariz y vuelve a los ojos.'],
  ['Mirada', 'Una mirada de unos segundos seguida de una sonrisa es una invitación suave a hablar.'],
  ['Mirada', 'Mirar al suelo o al móvil constantemente transmite inseguridad. Mira alrededor y sonríe.'],
  ['Mirada', 'Cuando alguien te mira un instante y aparta, no la sigas con la vista: un par de miradas bastan.'],
  ['Cuerpo', 'Una espalda recta y los hombros relajados hacen que te sientas y parezcas más seguro.'],
  ['Cuerpo', 'No cruces los brazos durante la conversación si quieres parecer abierto.'],
  ['Cuerpo', 'Inclínate un poco hacia quien habla: muestra interés. Sin pegarte.'],
  ['Cuerpo', 'Asiente de vez en cuando y ríete de lo que te hace gracia. El cuerpo comunica que escuchas.'],
  ['Cuerpo', 'Mantén las manos visibles y relajadas. Esconderlas transmite nervios.'],
  ['Cuerpo', 'Si hablas con alguien sentado, evita la mesa entre vosotros si puedes: una esquina da más cercanía.'],
  ['Cuerpo', 'Camina con calma, sin prisa y con la cabeza alta. Se nota.'],
  ['Voz', 'Baja un poco el volumen al hablar de cerca: transmite tranquilidad.'],
  ['Voz', 'Un tono cálido y pausado agrada más que uno acelerado.'],
  ['Voz', 'Respira antes de empezar a hablar: tu voz sale más estable.'],
  ['Voz', 'Evita muletillas como «o sea» o «tipo» en exceso: hacer una pausa es mejor.'],
  ['Voz', 'Cuando cuentes algo emocionante, deja que la voz lo transmita. La emoción engancha.'],
  ['Señales de interés', 'Si se ríe contigo y se queda cerca aunque el ambiente cambie, probablemente está a gusto.'],
  ['Señales de interés', 'Cuando alguien cuida de que lo pasas bien (te presenta, te incluye), suele haber aprecio.'],
  ['Señales de interés', 'Si te propone ir a un sitio sin que hayas dicho nada, hay ganas de pasar tiempo contigo.'],
  ['Señales de interés', 'Una persona interesada suele hablar de planes futuros en los que tú estás.'],
  ['Señales de interés', 'Si te escribe sin motivo («vi esto y pensé en ti»), te tiene presente.'],
  ['Señales de interés', 'Contestar rápido casi siempre y con más de una palabra suele indicar interés.'],
  ['Señales de interés', 'Si te hace cumplidos y no solo de aspecto, también valora cómo eres.'],
  ['Señales de poco interés', 'Si solo te escribe cuando necesita algo, puede que no busque más.'],
  ['Señales de poco interés', 'Si cancela y no vuelve a proponer, mejor dejarlo ir sin rencor.'],
  ['Señales de poco interés', 'Si te habla de otros chicos con ilusión, probablemente te ve como amigo.'],
  ['Señales de poco interés', 'Cuando se aparta al acercarte, respeta su espacio y no insistas.'],
  ['Señales de poco interés', 'Si no hace ninguna pregunta sobre ti en toda la conversación, hay poco interés.'],
  ['Conversación', 'Cuenta una anécdota con un principio, un giro y un final corto. Más no.'],
  ['Conversación', 'Pregunta por «lo mejor» y «lo peor» de algo: dan respuestas con emoción.'],
  ['Conversación', 'Cuando te cuente algo, pregunta «¿y cómo te sentiste?». Conecta más que «¿y qué pasó?».'],
  ['Conversación', 'Habla de lo que te apasiona con ganas: la pasión se contagia.'],
  ['Conversación', 'No interrumpas. Si lo haces sin querer, di: «Perdona, sigue».'],
  ['Conversación', 'Evita las preguntas tipo entrevista seguidas. Intercala con comentarios tuyos.'],
  ['Conversación', 'Los silencios de dos o tres segundos son normales. No los llenes con cualquier cosa.'],
  ['Conversación', 'Si no sabes qué decir, cuéntale lo que estás pensando: «Me estaba acordando de…».'],
  ['Conversación', 'Hablar de recuerdos de infancia y de lugares favoritos crea cercanía.'],
  ['Conversación', 'Evita los temas pesados (política dura, ex, dinero) al principio. Son fáciles de torcer.'],
  ['Conversación', 'Busca puntos en común: «¡A mí también me gusta eso!» une rápido.'],
  ['Conversación', 'Si te preguntan algo difícil, puedes decir «déjame pensarlo». Es mejor que una respuesta vacía.'],
  ['Mensajes', 'Un mensaje largo de golpe puede agobiar. Mejor frases cortas y dar espacio.'],
  ['Mensajes', 'Un audio corto a veces comunica más calidez que mil mensajes.'],
  ['Mensajes', 'Evita contestar enfadado. Espera, respira y escribe con calma.'],
  ['Mensajes', 'Una pregunta final facilita que te conteste: «¿Y tú qué tal?».'],
  ['Mensajes', 'No hace falta contestar siempre al instante: tu vida también cuenta.'],
  ['Mensajes', 'Las memes y los vídeos graciosos son buena forma de mantener el contacto ligero.'],
  ['Mensajes', 'Si llevas tiempo hablando por mensajes, propón vernos en persona antes de que se enfríe.'],
  ['Citas', 'Una cita pequeña (un café) permite conocerse sin invertir demasiado.'],
  ['Citas', 'Después de una cita, no hace falta esperar tres días. Un mensaje simpático ese mismo día va bien.'],
  ['Citas', 'Si la cita no va bien, no hay que alargarla. Termina con amabilidad.'],
  ['Citas', 'Fíjate en cómo trata a los camareros y a los demás: dice mucho.'],
  ['Citas', 'Pregunta qué le gusta hacer en su tiempo libre: abre mucho más que «¿a qué te dedicas?».'],
  ['Citas', 'No pienses en lo que pasará después. Disfruta del momento.'],
  ['Citas', 'Si hay química, se nota sin tener que forzar nada.'],
  ['Citas', 'Termina la cita antes de que se acabe el tema. Mejor con ganas de más.'],
  ['Citas', 'Ten una hora de salida clara: te da tranquilidad si hay nervios.'],
  ['Ansiedad', 'Respirar contando 4 segundos al coger aire y 6 al soltarlo calma el sistema nervioso.'],
  ['Ansiedad', 'La ansiedad sube antes de la situación, no en ella. Entrar suele ser lo más difícil.'],
  ['Ansiedad', 'Hacer ejercicio ligero antes de un plan reduce la ansiedad.'],
  ['Ansiedad', 'Evita mirarte constantemente («¿cómo lo estoy haciendo?»). Pon la atención fuera.'],
  ['Ansiedad', 'Tres cosas que oyes, tres que ves, tres que tocas: así vuelves al presente.'],
  ['Ansiedad', 'Si notas que sube, pon los pies firmes en el suelo y siente el peso.'],
  ['Ansiedad', 'Una frase útil: «Esto es incómodo, pero puedo con ello».'],
  ['Ansiedad', 'Cuanto más evitas una situación, más miedo da. Entrar poco a poco lo reduce.'],
  ['Ansiedad', 'La ansiedad no es peligrosa, aunque lo parezca. Sube, llega a un punto y baja.'],
  ['Ansiedad', 'Beber agua fría a sorbos ayuda a calmar el cuerpo.'],
  ['Alcohol', 'Si bebes, pide una bebida más lenta de beber: una caña dura más que un chupito.'],
  ['Alcohol', 'Cuando notes que ya estás a gusto, es el momento de parar o de pasar al agua.'],
  ['Alcohol', 'Si has bebido, evita conducir y confirma cómo vuelves a casa.'],
  ['Alcohol', 'El alcohol da seguridad prestada y se va con la resaca. La seguridad propia dura.'],
  ['Alcohol', 'Si usas alcohol para ligar con frecuencia, es buena idea hablarlo con tu psicóloga.'],
  ['Alcohol', 'Con alcohol, dos personas no pueden consentir bien. Mejor dejarlo para otro día.'],
  ['Salir', 'Quedaos antes de ir a un sitio grande: llegáis más soltos.'],
  ['Salir', 'Elige un sitio que te guste, no el de moda. Te sentirás más tú.'],
  ['Salir', 'Una noche tranquila con conversaciones buenas puede valer más que una noche loca.'],
  ['Salir', 'Si la noche va mal, cambia de plan: otro bar, un paseo o a casa. No hay que aguantar.'],
  ['Salir', 'Ten una cosa que decir cuando alguien te pregunte «¿qué tal?» además de «bien».'],
  ['Salir', 'Si ves a alguien con quien te gustaría hablar, ten claro que ya has ganado si te acercas.'],
  ['Autoestima', 'Dedícate un rato a cosas que te gustan sin culpa. Es tiempo bien invertido.'],
  ['Autoestima', 'Háblate como le hablarías a un amigo en tu situación.'],
  ['Autoestima', 'Cada cosa pequeña que haces por ti suma: ducharte, comer bien, salir.'],
  ['Autoestima', 'No necesitas la aprobación de todos. Con la de personas que te quieren, basta.'],
  ['Autoestima', 'Recuerda tus logros: el último año has mejorado mucho socialmente.'],
  ['Autoestima', 'Los errores son parte del aprendizaje. Si no te equivocas, no aprendes.'],
  ['Autoestima', 'Cuando te critiques, pregúntate: ¿se lo diría a alguien que quiero?'],
  ['Autoestima', 'Elige personas que te hagan sentir bien contigo.'],
  ['Autoestima', 'La confianza real es poder equivocarte y seguir siendo tú.'],
  ['Cabeza', 'Los pensamientos no son hechos. Que pienses «voy a hacer el ridículo» no significa que pase.'],
  ['Cabeza', 'Imagina cómo te sentirías si todo saliera bien. Te prepara mejor que imaginar lo malo.'],
  ['Cabeza', 'Repasar mentalmente lo que dijiste después de un plan no ayuda. Mejor haz otra cosa.'],
  ['Cabeza', 'Piensa en el peor escenario real: casi nunca es tan malo ni tan probable.'],
  ['Cabeza', 'Cada experiencia, buena o mala, te da datos para el futuro.'],
  ['Cabeza', 'Prueba a convertir «tengo que» en «voy a intentar». Baja la presión.'],
  ['Intimidad', 'Después de un momento íntimo, un abrazo y una conversación tranquila son importantes.'],
  ['Intimidad', 'No hay una forma «correcta». Cada pareja encuentra la suya hablando.'],
  ['Intimidad', 'Si algo no ha salido como esperabas, hablarlo con cariño os une más.'],
  ['Intimidad', 'Los nervios al principio son normales. Con confianza mejoran.'],
  ['Intimidad', 'El consentimiento es entusiasta, claro y se puede retirar en cualquier momento.'],
  ['Barcelona', 'Los vermuts de domingo en Sant Antoni, Gràcia o Poble Sec son plan clásico y relajado.'],
  ['Barcelona', 'Salas pequeñas como las de Poble Sec, Raval o Gràcia son perfectas para planes musicales.'],
  ['Barcelona', 'Para citas diurnas: Parc de la Ciutadella, jardins de Montjuïc o el Bunker del Carmel.'],
  ['Barcelona', 'Los mercados de segunda mano y de barrio dan mucho tema y poca presión.'],
  ['Barcelona', 'Los cursos cortos de cocina, cerámica o fotografía son de los mejores sitios para conocer gente.'],
  ['Barcelona', 'Los grupos de senderismo y de running por la ciudad son abiertos y sociales.'],
  ['Barcelona', 'Los bares con juegos de mesa son planes sencillos que funcionan muy bien con desconocidos.'],
  ['Barcelona', 'En Barcelona se queda tarde (cenas a las 21-22 h). Ajusta el plan y no te agobies por la hora.'],
  ['Amistad', 'Una amistad se construye con tiempo compartido y detalles pequeños.'],
  ['Amistad', 'Escribe a un amigo sin motivo: «Me acordé de ti». Los fortalece mucho.'],
  ['Amistad', 'Ser tú quien propone planes es una cualidad, no un defecto.'],
  ['Amistad', 'Amigos de varios mundos (trabajo, música, deporte) amplían tu vida.'],
  ['Amistad', 'No todos los amigos tienen que servir para todo. Cada uno aporta algo.'],
  ['Humor', 'El humor más atractivo es el amable: reírte con los demás, no de ellos.'],
  ['Humor', 'Una anécdota en la que tú sales mal parado hace simpatía.'],
  ['Humor', 'Observa lo que pasa a tu alrededor y comenta con ironía suave.'],
  ['Humor', 'Si no sale gracioso, sonríe: la tensión se va.'],
  ['Bienestar', 'Pasar tiempo con amigos que te hacen reír baja el estrés.'],
  ['Bienestar', 'Mirar el cielo o pasear cinco minutos sin móvil te asienta.'],
  ['Bienestar', 'Escribir en un diario antes de dormir ayuda a soltar lo del día.'],
  ['Bienestar', 'Una ducha con agua templada después de un día intenso afloja la tensión.'],
  ['Bienestar', 'Cuida tu rutina de sueño los días antes de un plan importante.'],
  ['Presencia', 'Habla de manera que la otra persona se sienta cómoda. Eso transmite seguridad.'],
  ['Presencia', 'Vestirte con cuidado para una cita es una muestra de respeto, no de vanidad.'],
  ['Presencia', 'La sonrisa sincera es la mejor «ropa» que tienes.'],
  ['Presencia', 'Alguien con presencia no necesita demostrar nada: escucha y está.'],
  ['Rechazo', 'Cuantos más «no» recibes, menos te asustan. Es entrenamiento.'],
  ['Rechazo', 'Si te dicen que no, di «gracias por decírmelo». Muy elegante.'],
  ['Rechazo', 'Fija un objetivo de «intentos» por mes, no de «sí». Así siempre avanzas.'],
  ['Rechazo', 'Un rechazo no significa que no valgas: significa que no hay encaje con esa persona.'],
  ['Ropa', 'Una buena camisa blanca o una camiseta básica de calidad son la base de muchos looks.'],
  ['Ropa', 'Zapatillas blancas limpias o botas sencillas suben cualquier outfit.'],
  ['Ropa', 'Cuida el ajuste: ni demasiado holgado ni apretado. Pide al sastre arreglos baratos.'],
  ['Ropa', 'Un perfume suave y que te guste da seguridad a ti.'],
  ['Primera cita', 'Elige un sitio con buena luz y no demasiado ruidoso.'],
  ['Primera cita', 'No hace falta mucho: unas cañas o un café bastan para saber si hay conexión.'],
  ['Primera cita', 'Pregunta por su día y escucha de verdad. Eso se recuerda.'],
  ['Pareja temprana', 'Respetad los tiempos de cada uno. Ir con calma suele dar mejor resultado.'],
  ['Pareja temprana', 'Decir «me lo paso muy bien contigo» es sencillo y muy bonito.'],
  ['Pareja temprana', 'Evita comparar con parejas anteriores. Cada relación es distinta.'],
  ['Dinero', 'Invita a un café o a una caña a veces: es un detalle sin presión.'],
  ['Dinero', 'Si no os apetece gastar, un paseo y un helado también es un plan estupendo.'],
  ['Redes', 'Subir fotos tuyas sonriendo y haciendo algo que te gusta dice más que un selfie en el baño.'],
  ['Redes', 'Responde a historias con algo concreto y no solo con un emoji.'],
  ['Redes', 'Si te sientes mal tras mirar redes, déjalas un rato. No es obligatorio estar.']
);

/* Rehacer «Tips rápidos» con todos los tips cargados */
(() => {
  const d = DOCS.find(x => x.id === 'd-tips');
  if (d) { d.sub = 'Cientos de consejos cortos, por temas'; d.secciones = [...new Set(TIPS.map(t => t[0]))].map(c => [c, TIPS.filter(t => t[0] === c).map(t => t[1])]); }
})();
