/* Contenido ampliado: documentos de consulta, situaciones concretas, «Para ti» y «Conócete».
   Todo genérico: lo personal lo eliges tú en el móvil (perfil) y no sale de él. */
'use strict';

/* ---------- Documentos: se leen de arriba abajo, con apartados cortos ---------- */
const DOCS = [
  { id:'d-barcelona', grupo:'bcn', icono:'🏙️', titulo:'Ligar en Barcelona a tu edad', sub:'Cómo se conoce gente hoy, dónde, costumbres y apps', secciones:[
    ['Cómo está el panorama', ['Entre los 25 y los 35, en Barcelona se conoce gente sobre todo por tres vías: amigos de amigos, actividades que se repiten (cursos, deporte, voluntariado) y apps.', 'Hay muchísima gente de fuera: de otras ciudades de España y de otros países. Eso hace que mucha gente también esté buscando conocer a otros, y que sea normal hablar con desconocidos en según qué ambientes.', 'A esta edad hay de todo: gente que busca algo serio, gente que solo quiere conocer y gente que acaba de salir de una relación larga. No tienes que adivinarlo: se ve hablando.', 'No eres el único que empieza tarde o que tiene poca experiencia. Es más común de lo que parece, aunque nadie lo diga.']],
    ['Dónde conocer gente (lo que mejor funciona)', ['Algo que se repite cada semana: la repetición crea confianza sin esfuerzo. Un curso, un club, un equipo.', 'Clubes de correr (hay varios gratuitos que salen de la playa o de parques), escalada en rocódromo, pádel, yoga, baile (salsa, bachata, swing).', 'Intercambios de idiomas: muy típicos en Barcelona, gente abierta a hablar con desconocidos y con un tema ya dado.', 'Cursos: cocina, fotografía, teatro, improvisación (esta última, muy útil para la ansiedad social), catalán.', 'Voluntariado: bancos de alimentos, protectoras, actividades con mayores.', 'Grupos de aficiones (música, juegos de mesa, senderismo los fines de semana, fútbol para ver partidos).', 'Amigos de amigos: di a tus amigos que te apetece conocer gente nueva. Mucha gente lo hace y funciona.']],
    ['Zonas y ambientes', ['Gràcia: plazas, terrazas y ambiente tranquilo y alternativo. Bueno para un primer café o unas cañas.', 'Sant Antoni y Poble-sec: vermut, tapas y bares de barrio. Muy cómodo para una primera cita.', 'Born y Gòtic: bares con encanto, pero muchos turistas y más ruido.', 'Eixample: bares y restaurantes de todo tipo; algo más arreglado.', 'Poblenou: tranquilo, la Rambla del Poblenou y la playa cerca.', 'Raval: alternativo y animado; de noche, más jaleo.', 'Para pasear: Montjuïc, el Turó de la Rovira (Búnkers del Carmel) al atardecer, la playa, Parc de la Ciutadella.']],
    ['Costumbres que conviene saber', ['Se cena tarde (21-22 h) y se sale más tarde aún. La fiesta empieza a partir de la 1.', 'Para conocer a alguien sin presión, de día es más fácil: café, vermut, un paseo.', 'Al saludar, dos besos es lo habitual; con gente de fuera, a veces un abrazo o la mano. Si dudas, sigue lo que haga la otra persona.', 'Mucha gente habla catalán. No hace falta que lo hables, pero mostrar interés (un «bon dia», una pregunta) suele caer bien.', 'Pagar: lo más común es a medias o alternar. No es un tema de primera cita.']],
    ['Las apps', ['Tinder: la más usada, de todo un poco. Hinge: más orientada a conocer en serio y con preguntas que ayudan a empezar a hablar. Bumble: en citas, ella escribe primero.', 'Fotos: 4 o 5, recientes, con luz natural. Al menos una sonriendo, una de cuerpo entero y alguna haciendo algo que te guste. Sin gafas de sol en todas y sin solo selfies.', 'Biografía: corta, concreta y con algo con lo que empezar a hablar («Busco el mejor vermut de Sant Antoni, acepto recomendaciones»).', 'Empezar a hablar: comenta algo concreto de su perfil y haz una pregunta. Mejor que «hola, ¿qué tal?».', 'Pocos matches es lo normal, sobre todo para los hombres. No es una medida de lo que vales: las apps funcionan así para casi todo el mundo.', 'Después de unos días hablando bien, propón quedar. Las apps sirven para conocerse en persona, no para escribirse eternamente.']]
  ]},
  { id:'d-edades', grupo:'bcn', icono:'🧭', titulo:'Según la edad y el tipo de persona', sub:'Tendencias, no reglas: cada persona es distinta', secciones:[
    ['Antes de nada', ['Todo lo de aquí son tendencias generales. La persona que tienes delante puede ser justo lo contrario. Lo que manda es lo que ves al conocerla.']],
    ['Según la edad', ['Más o menos de tu edad: es lo más sencillo, porque compartís momento vital (trabajo, piso, planes).', 'Algo más jóvenes (23-26): suele haber más vida social y fiesta; a veces menos ganas de algo serio. No es mejor ni peor.', 'Algo mayores (32-38): más claridad sobre lo que buscan y menos paciencia con los juegos. La sinceridad se valora mucho.', 'Una diferencia de pocos años es normal. Con diferencias grandes, fíjate en si compartís momento de vida.']],
    ['Según el tipo de persona', ['Más tímida o introvertida: planes tranquilos y para dos; dale tiempo para abrirse y no llenes cada silencio. Puede que encajéis muy bien.', 'Muy sociable o extrovertida: suele hablar con todo el mundo, así que la simpatía no es señal de interés por sí sola. Planes con algo de actividad.', 'Gente de fuera de España: curiosidad por la ciudad y las costumbres. Recomendar sitios o enseñar un rincón es buen plan. Si habláis en inglés, no hace falta hablarlo perfecto.', 'Alguien muy centrada en su trabajo o estudios: valora la claridad y los planes concretos con fecha.', 'Alguien que acaba de salir de una relación: puede que no esté para nada serio. Mejor ir despacio y preguntar con naturalidad.']],
    ['Según cómo os conocéis', ['Por amigos: hay confianza de base, pero cuida no incomodar al grupo si no sale.', 'Por una actividad: tienes tiempo. Primero, ser alguien con quien se habla a gusto; luego, proponer algo fuera de la actividad.', 'Por una app: los dos sabéis a qué vais, así que se puede ser más directo con quedar.', 'En el trabajo: mucho cuidado (ver «En el trabajo» en Situaciones).']]
  ]},
  { id:'d-cuando', grupo:'ligar', icono:'🚦', titulo:'Cuándo intentarlo y cuándo no', sub:'Cómo mostrar interés con respeto, y cuándo es mejor no hacerlo', secciones:[
    ['Cómo se muestra interés, paso a paso', ['1. Hablar con normalidad, como con cualquiera.', '2. Mostrar interés por ella: preguntas, recordar lo que te cuenta, buscarla para hablar.', '3. Dejar ver que te gusta, sin presión: «Me lo paso muy bien hablando contigo».', '4. Proponer algo concreto para dos.', '5. Según cómo responda, seguir o dejarlo estar.', 'Cada paso le da la oportunidad de responder. No hace falta saltarse ninguno.']],
    ['Buen momento', ['Cuando ya habéis hablado varias veces y la conversación fluye.', 'Cuando ella también te busca, te pregunta cosas o se queda hablando.', 'Cuando hay un motivo natural: algo que os gusta a los dos, un plan del que habéis hablado.', 'Cuando estáis en un sitio relajado y ella no tiene prisa.']],
    ['Mejor no', ['Si está trabajando y te atiende (camarera, dependienta, médica…): es su trabajo, y no puede irse.', 'Si lleva auriculares, está con prisa o claramente concentrada en otra cosa.', 'Si ha bebido mucho.', 'Si sabes que tiene pareja.', 'Si ya te dijo que no, o sus respuestas son siempre cortas.', 'Si hay una relación de jerarquía (jefe-subordinada, profesor-alumna).', 'Si está pasando por algo duro (un duelo, una ruptura reciente) y no te ha dado pie.', 'En la calle o en el transporte con desconocidas: casi siempre incomoda. Mejor sitios donde la gente está para socializar.']],
    ['Cuándo parar', ['Cuando te dice que no, aunque sea suave («no sé», «estoy liada», «ya veremos» sin proponer nada).', 'Cuando has propuesto algo dos veces y no hay respuesta clara ni alternativa.', 'Cuando notas que se aparta o le incomoda.', 'Parar a tiempo es lo que hace que la otra persona se quede con buena imagen de ti.']]
  ]},
  { id:'d-gusto', grupo:'ligar', icono:'🔍', titulo:'¿Le gusto, le caigo bien o nada?', sub:'Cómo distinguirlo, y cómo saber si algo falla', secciones:[
    ['Tres cosas distintas', ['Le caes bien: está a gusto contigo, habla de buen humor, es amable. Puede ser así con todo el mundo.', 'Le atraes: además de lo anterior, te busca, propone, se acuerda de detalles, alarga los momentos, y a veces busca algo de contacto.', 'No hay interés: respuestas cortas, no te pregunta nada, no propone nada, cancela sin dar otra fecha.']],
    ['Señales de que le caes bien', ['Te saluda con ganas y sonríe al verte.', 'Te cuenta cosas suyas y se ríe de tus bromas.', 'Te incluye en planes de grupo.']],
    ['Señales de que puede haber algo más', ['Te escribe ella también y a veces empieza la conversación.', 'Propone o acepta planes para dos con ganas y concreta fechas.', 'Se acuerda de lo que le contaste y te pregunta por ello.', 'Busca estar cerca, alarga las despedidas, toca algo el brazo al hablar.', 'Varias de estas a la vez y repetidas en el tiempo. Una sola no dice casi nada.']],
    ['Señales de que no hay interés (o no por ahora)', ['Respuestas cortas que no hacen preguntas.', 'Tarda mucho en contestar siempre, no solo alguna vez.', 'Dice «ya veremos» o «estoy liada» y no propone otro día.', 'Te trata igual que a todo el mundo, sin buscarte.']],
    ['La única forma de saberlo', ['Dar un paso pequeño y claro (proponer un plan) y ver qué responde. Las señales dan pistas; la respuesta a un paso concreto da la verdad.']],
    ['Si sientes que no atraes en general', ['Nadie atrae a todo el mundo, y casi todos pasan rachas en las que nada sale.', 'Mira lo que sí depende de ti: dónde conoces gente (¿sitios donde se repite el trato?), cómo te presentas (fotos, ropa que te queda bien, higiene), y si das pasos claros o esperas a que pase solo.', 'Pide opinión sincera a una amiga o amigo de confianza: «¿Qué cambiarías de mis fotos?», «¿Cómo me ves cuando hablo con gente nueva?».', 'Ser buena persona no es lo mismo que mostrar interés. A veces caes muy bien pero nadie sabe que te gusta: falta dar el paso.']]
  ]},
  { id:'d-nervios', grupo:'ligar', icono:'🫶', titulo:'Inseguridades y nervios con chicas', sub:'De dónde salen y qué hacer con ellos', secciones:[
    ['Por qué pasa', ['Cuanto más te importa algo, más nervios. Que te pongas nervioso con alguien que te gusta es normal, no un defecto.', 'Con poca experiencia, el cerebro no tiene «datos» de que sale bien, así que imagina lo peor. Los datos se consiguen haciéndolo.', 'Las inseguridades hablan más alto que la realidad: lo que tú ves como defecto, la otra persona casi nunca lo nota.']],
    ['Inseguridades típicas y qué decirte', ['«No tengo experiencia»: no se nota hablando, y no hace falta contarlo en una primera cita. Si sale, la verdad sencilla basta: «No he tenido muchas relaciones».', '«No soy atractivo»: el físico pesa menos de lo que crees después de los primeros minutos (mira la lección de atracción).', '«No tengo nada interesante que contar»: a la gente le interesa sentirse escuchada más que oír historias increíbles.', '«Voy a hacer el ridículo»: quizá algo salga torpe. A todo el mundo le pasa, y casi nadie se acuerda al día siguiente.', '«Soy demasiado mayor para empezar»: no hay edad para esto. Hay gente que empieza a los 35 o a los 40 y le va bien.']],
    ['Antes de ver a alguien', ['Haz algo que te calme: caminar, música, ducha. Llega con tiempo.', 'Piensa en ella como persona, no como examen: también estará nerviosa.', 'Ponte un objetivo pequeño: pasarlo bien un rato, no «que salga perfecto».']],
    ['Durante', ['Si notas los nervios, suelta el aire largo y pon la atención en lo que te cuenta.', 'Puedes decirlo: «Estoy un poco nervioso, jaja». Desactiva mucho.', 'Si te equivocas o dices algo raro, una sonrisa y sigue. No hace falta arreglarlo.']],
    ['Después', ['No repases la conversación buscando errores. Quédate con lo que salió bien.', 'Apúntalo en tu diario como victoria. Ir ya es lo difícil.']],
    ['Sobre tu salud y la terapia', ['No hace falta hablar de tu ansiedad, de la terapia o de la medicación en las primeras citas. Es información tuya y la cuentas cuando haya confianza, si quieres.', 'Cuando lo cuentes, puedes hacerlo con naturalidad: «Voy a terapia, me ayuda mucho». Hoy es muy habitual y suele verse bien.']]
  ]},
  { id:'d-chuleta', grupo:'ligar', icono:'📋', titulo:'Chuleta: qué decir y cómo actuar', sub:'Frases para cada momento, listas para usar', secciones:[
    ['Saludar y presentarte', ['«Hola, soy ___. ¿Tú eres…?»', '«Encantado, ___» (repite su nombre, ayuda a recordarlo).', 'Cómo: mira a la cara, sonrisa corta, voz tranquila. Dos besos o lo que haga ella.']],
    ['Empezar a hablar', ['«¿De qué conoces a ___?»', '«¿Es tu primera vez aquí?»', '«¿Sabes si esto empieza a las ocho?»', '«Qué buena pinta tiene eso, ¿qué es?»']],
    ['Mantener la conversación', ['Preguntas abiertas (que no se contestan con sí o no): «¿Y cómo acabaste trabajando en eso?», «¿Qué es lo que más te gusta de…?»', 'Seguir el hilo: «¿Y eso cómo fue?», «¿Y qué pasó al final?»', 'Compartir algo tuyo relacionado: «A mí me pasó algo parecido cuando…»', 'Temas que casi siempre funcionan: trabajo o estudios (sin interrogar), planes del finde, viajes, comida, series, música, la ciudad.', 'Mejor evitar al principio: exparejas, política dura, dinero, quejas largas.']],
    ['Un cumplido que sienta bien', ['Sobre lo que hace o dice: «Qué bien lo explicas», «Tienes muy buen gusto para la música».', 'Sobre su estilo, sin pasarse: «Me gusta mucho tu chaqueta».', 'Sobre el físico, mejor cuando ya hay confianza, y sin centrarse en el cuerpo.']],
    ['Si te quedas en blanco', ['«Antes has dicho que… ¿cómo fue?»', '«Me he quedado en blanco, jaja. ¿Qué me decías de…?»', 'Una pausa también vale. No pasa nada.']],
    ['Pedir el contacto', ['«¿Me pasas tu Instagram? Así te mando lo que te dije.»', '«Me ha gustado mucho hablar contigo. ¿Te importa si te pido el número?»']],
    ['Proponer un plan', ['«¿Te apetece tomar algo esta semana? ¿El jueves te va bien?»', '«Has dicho que no has ido a ___. ¿Vamos el sábado?»']],
    ['En la cita', ['Al llegar: «¡Hola! Qué bien que hayas venido.»', 'Para elegir sitio: «¿Te va bien aquí o prefieres otro?»', 'Para pagar: «¿Lo pagamos a medias?» o «Esta la pago yo, y la siguiente tú.»', 'Si te apetece darle un beso: «¿Te puedo dar un beso?» (y solo con un sí claro).', 'Para terminar: «Me lo he pasado muy bien. ¿Repetimos?»']],
    ['Después', ['Mensaje: «Me lo pasé muy bien ayer, gracias por el plan.»', 'Si no quieres repetir: «Me lo pasé bien, pero no siento que vaya a más. Te deseo lo mejor.»']],
    ['Si te dicen que no', ['«Vale, sin problema.» Y sigues normal o te despides con amabilidad.']],
    ['Si tienes que cancelar', ['«Lo siento, me ha surgido algo y no puedo hoy. ¿Te va bien el jueves?» Siempre con otra fecha si quieres seguir.']],
    ['Cómo actuar en general', ['Hombros sueltos, cuerpo hacia la otra persona, móvil guardado.', 'Habla un poco más despacio de lo que te sale con nervios.', 'Escucha de verdad: asiente, reacciona, pregunta.', 'Sonríe al saludar y al despedirte. No hace falta sonreír todo el rato.']]
  ]},
  { id:'d-trucos', grupo:'yo', icono:'🧠', titulo:'Trucos psicológicos para ti', sub:'Cosas pequeñas que funcionan, con base en la psicología', secciones:[
    ['Para la ansiedad en el momento', ['Llama a los nervios «emoción»: decirte «estoy emocionado» en vez de «estoy nervioso» ayuda a rendir mejor (se ha estudiado en hablar en público).', 'Suelta el aire más largo de lo que lo coges: frena el cuerpo en segundos.', 'Pon nombre a lo que sientes: «Esto es ansiedad». Nombrarlo baja su intensidad.', 'Atención fuera: fíjate en lo que dice la otra persona, en sus palabras y su cara. Cuanto más miras fuera, menos ruido hay dentro.', 'Cuenta atrás 5-4-3-2-1 y haz lo que ibas a hacer antes de que la cabeza encuentre excusas.', 'Las manos ocupadas (una bebida, apoyadas en la mesa) dan seguridad, pero no te escondas tras el móvil.']],
    ['Para la autoestima', ['Háblate en segunda persona o por tu nombre: «Venga, tú puedes con esto». Crea distancia y se piensa con más calma.', 'Apunta cada noche tres cosas que hiciste bien, por pequeñas que sean. Con las semanas, cambia cómo te ves.', 'Compárate solo con quien eras hace unos meses, no con los demás.', 'Trátate como a un amigo: si no se lo dirías a otro, no te lo digas a ti.', 'Las acciones cambian lo que sientes, no al revés. No esperes a sentirte seguro para hacer algo: hazlo y la seguridad viene después.']],
    ['Para la conversación', ['El efecto foco: la gente se fija muchísimo menos en ti de lo que crees. Todos están pendientes de sí mismos.', 'Di el nombre de la otra persona alguna vez: a todos nos gusta oírlo.', 'Las preguntas de seguimiento («¿y luego?», «¿cómo fue?») hacen que la otra persona te vea más agradable, según varios estudios.', 'Acuérdate de un detalle y pregúntalo otro día: «¿Qué tal te fue la entrevista?». Deja muy buena huella.', 'Termina bien: la gente recuerda sobre todo el mejor momento y el final. Despídete en un buen momento, no cuando la conversación ya se ha apagado.', 'Pedir un favor pequeño («¿me recomiendas un sitio?») crea cercanía: a la gente le gusta ayudar.', 'Encontrar algo en común, aunque sea pequeño, acerca muchísimo: «¿Tú también eres de los que…?».', 'Escuchar más que hablar no te hace aburrido: te hace alguien con quien es fácil estar.']],
    ['Para hacer las cosas', ['«Si pasa X, haré Y»: decide de antemano. «Si veo a mi vecina en el ascensor, la saludo primero.» Así no dependes de las ganas.', 'Hazlo muy pequeño: dos minutos, un saludo, una pregunta. Lo pequeño se hace; lo grande se aplaza.', 'Pega lo nuevo a algo que ya haces: «Después del café de la mañana, escribo un mensaje a alguien».', 'Celebra al terminar, aunque sea por dentro. El cerebro repite lo que se premia.']],
    ['Para pensar con más claridad', ['Peor, mejor y más probable: imagina las tres versiones. Casi siempre la más probable es bastante normal.', '¿Importará dentro de un año? Si no, no merece tantas vueltas.', 'Separa hechos de interpretaciones: «no ha contestado» es un hecho; «no le intereso» es una interpretación.', 'Antes de un plan, piensa qué podría salir mal y qué harías. Tener respuesta preparada quita miedo.']],
    ['Lo que no son estos trucos', ['No son para manipular a nadie. Sirven para que tú estés más tranquilo y la otra persona más a gusto. Todo lo que implique engañar o presionar, fuera.']]
  ]},
  { id:'d-conocete', grupo:'yo', icono:'🪞', titulo:'Conócete y descubre cómo te ven', sub:'Ejercicios sencillos para mirarte desde fuera', herramienta:true, secciones:[
    ['Por qué sirve', ['Cuanto mejor sabes lo que te gusta, lo que valoras y cómo te perciben, más fácil es elegir dónde estar, de qué hablar y con quién encajas.']],
    ['Ejercicios (los puedes rellenar abajo)', ['Tus valores: elige los 5 que más te importan. Te ayudan a saber qué buscas en otra persona.', 'Tus puntos fuertes: elige los que te reconoces, aunque te dé vergüenza.', 'Cómo te ven: pide a 3 personas de confianza «Dime tres palabras que me describan». Apúntalas. Suele sorprender lo positivas que son.', 'Lo que te gusta hacer: apunta planes y temas que te encienden. Son tus temas de conversación y tus sitios para conocer gente.']],
    ['Otros ejercicios', ['Grábate un minuto hablando de algo que te gusta. Míralo como si fuera un amigo: casi siempre se te ve mejor de lo que crees.', 'Mira fotos tuyas recientes con alguien de confianza y pregúntale cuáles te representan mejor (sirve también para las apps).', 'Apunta durante una semana cuándo tienes más y menos energía social. Así sabrás cuándo quedar y cuándo descansar.', 'Haz un test de personalidad de los «cinco grandes rasgos» (Big Five). Hay versiones gratuitas y serias. Es una foto, no una etiqueta.', 'Pregunta a un amigo o amiga: «Cuando hablo con gente nueva, ¿hay algo que te llame la atención?». Pide una cosa buena y una a mejorar.']]
  ]}
];

/* Valores y puntos fuertes para elegir en «Conócete» */
const VALORES = ['Honestidad', 'Lealtad', 'Familia', 'Amistad', 'Libertad', 'Tranquilidad', 'Aprender', 'Humor', 'Respeto', 'Justicia', 'Creatividad', 'Aventura', 'Estabilidad', 'Salud', 'Esfuerzo', 'Generosidad', 'Naturaleza', 'Cultura', 'Independencia', 'Cuidar a otros'];
const FUERTES = ['Escucho bien', 'Soy leal', 'Soy detallista', 'Soy constante', 'Soy sincero', 'Soy amable', 'Tengo buen humor', 'Soy curioso', 'Cocino bien', 'Sé mucho de música', 'Sé de deporte', 'Soy ordenado', 'Me esfuerzo', 'Soy paciente', 'Soy fiable', 'Tengo buen gusto', 'Soy tranquilo', 'Me preocupo por los demás'];

/* ---------- Situaciones en sitios concretos (bloque 5 de la guía) ---------- */
const GUIA_EXTRA = { bloque:'En sitios y momentos concretos', items:[
  { id:'g-bar', titulo:'En un bar, una terraza o de fiesta',
    pasa:'Hay mucha gente, ruido y grupos ya formados. Acercarse a alguien parece imposible.',
    hacer:['Es más fácil si vas con amigos y os mezcláis con otro grupo que con una persona sola.', 'Momentos naturales: en la barra pidiendo, en la cola, si alguien de tu grupo conoce a alguien del suyo.', 'Empieza con algo del sitio: «¿Has probado el vermut de aquí?», «¿Sabes a qué hora toca el grupo?».', 'Si ella está con amigas, incluye a todas en la conversación. Es menos invasivo y más relajado.'],
    ejemplos:[], cierre:'',
    extra:[['Mejor no', ['Interrumpir una conversación íntima entre amigas.', 'Volver a intentarlo si ya te contestó corto.']]],
    sale:'Si no sale nada, has estado en un sitio con gente, y eso ya es práctica.',
    practica:'Comentar algo del sitio a alguien en la barra o en la cola' },
  { id:'g-actividad', titulo:'En un curso, un club o una actividad',
    pasa:'Es el mejor sitio para conocer a alguien: os veis a menudo y tenéis un tema en común. Pero da miedo «estropear» el ambiente.',
    hacer:['Tienes tiempo. Primero, ser alguien con quien se habla a gusto: saludar, comentar la clase, preguntar.', 'Proponer algo de grupo es fácil y sin presión: «¿Alguien se apunta a tomar algo después?».', 'Si con alguien hay especial buen rollo durante semanas, proponer algo para dos: «¿Te apetece que vayamos a ___?».'],
    ejemplos:[], cierre:'',
    extra:[['Mejor no', ['Ir solo para ligar y no por la actividad: se nota.', 'Insistir si no hay respuesta: luego os seguís viendo cada semana.']]],
    sale:'Aunque no surja nada, ganas amistades y un sitio donde estar a gusto.',
    practica:'Proponer tomar algo después de una actividad, a todo el grupo' },
  { id:'g-trabajo', titulo:'En el trabajo',
    pasa:'Pasas muchas horas con las mismas personas y es normal que alguien te guste. Pero aquí un error pesa más, porque os seguís viendo cada día.',
    hacer:['Ve mucho más despacio que en otros sitios. Primero, compañerismo normal.', 'Si hay mucha complicidad durante tiempo, un plan casual fuera del trabajo, mejor en grupo al principio.', 'Si das un paso y la respuesta no es un sí claro, no se vuelve a intentar, y la tratas igual que siempre.'],
    ejemplos:[], cierre:'',
    extra:[['Nunca', ['Si hay jerarquía entre vosotros (tú mandas sobre ella o al revés).', 'Comentarios sobre su físico en el trabajo.', 'Mensajes fuera del trabajo si ella no los ha buscado.']]],
    sale:'Si no surge, mantén la profesionalidad. Eso dice muchísimo de ti.',
    practica:'Ser yo quien propone un café o una comida con compañeros' },
  { id:'g-gym', titulo:'En el gimnasio',
    pasa:'Ves a la misma gente a menudo, pero casi todo el mundo va a lo suyo, con auriculares y concentrado.',
    hacer:['Saludar con la cabeza o un «hola» a quien ves siempre ya crea familiaridad.', 'Si un día hay un momento natural (compartir una máquina, una clase dirigida), una frase corta y amable.', 'En las clases dirigidas es más fácil hablar antes o después.'],
    ejemplos:[], cierre:'',
    extra:[['Mejor no', ['Interrumpir a alguien entrenando o con auriculares.', 'Dar consejos de técnica que no te han pedido.', 'Mirar fijamente.']]],
    sale:'Si no surge, el gimnasio sigue siendo tu sitio. No pasa nada.',
    practica:'Saludar a alguien a quien veo a menudo en el gimnasio' },
  { id:'g-intercambio', titulo:'En un intercambio de idiomas o un evento para conocer gente',
    pasa:'Es de los sitios más fáciles: todo el mundo ha ido para hablar con desconocidos.',
    hacer:['Llega pronto: con menos gente es más fácil empezar.', 'La pregunta de siempre funciona: «¿De dónde eres? ¿Cuánto llevas en Barcelona?».', 'Habla con varias personas, no solo con una. Luego es más fácil volver a quien te ha caído bien.', 'Si te gusta alguien, al final: «¿Vienes la semana que viene?» o pedir el Instagram.'],
    ejemplos:[], cierre:'', extra:[],
    sale:'Si una noche no conectas con nadie, la semana siguiente habrá caras conocidas.',
    practica:'Ir una vez a un intercambio de idiomas o a un evento para conocer gente' },
  { id:'g-alcohol', titulo:'Cuando hay alcohol de por medio',
    pasa:'Beber relaja y da valor, así que es tentador usarlo para atreverte.',
    hacer:['Una o dos copas como mucho. Con más, se habla peor, se leen peor las señales y al día siguiente la ansiedad sube.', 'Alterna con agua o refrescos. Nadie se fija en lo que bebes.', 'Si ella ha bebido mucho, no es el momento de nada más que una conversación amable. El consentimiento con mucho alcohol no vale.'],
    ejemplos:[], cierre:'', extra:[],
    sale:'Si bebiste de más y dijiste algo de lo que te arrepientes, una disculpa sencilla al día siguiente basta.',
    practica:'Ir a un plan y tomar como mucho dos copas' },
  { id:'g-pareja', titulo:'Si te gusta alguien que tiene pareja',
    pasa:'Pasa a menudo, y es normal sentirlo. Lo que importa es lo que haces con ello.',
    hacer:['Puedes ser su amigo con normalidad, si eso no te hace daño.', 'No intentes nada mientras tenga pareja. Si algún día está soltera, ya se verá.', 'Si te duele demasiado verla, está bien tomar algo de distancia.'],
    ejemplos:[], cierre:'', extra:[],
    sale:'Sentir algo que no puedes llevar a cabo es duro, y se pasa. Llévalo a terapia si te pesa.',
    practica:'Fijarme en otras personas con las que sí puede surgir algo' },
  { id:'g-amiga', titulo:'Si te gusta una amiga',
    pasa:'Te da miedo perder la amistad si le dices algo.',
    hacer:['Fíjate en las señales: ¿te busca a solas, te habla de forma distinta que a los demás, propone planes para dos?', 'Si crees que puede haber algo, un paso suave: proponer un plan «de cita» (una cena para dos) y ver cómo responde.', 'Si quieres decírselo, que sea en persona, sencillo y sin presión: «Me gustas, y no quería quedarme sin decírtelo. Si no sientes lo mismo, no pasa nada, quiero seguir siendo tu amigo.»'],
    ejemplos:[], cierre:'', extra:[],
    sale:'Si no siente lo mismo, la amistad suele sobrevivir si tú la tratas igual que antes. Puede que necesites un poco de distancia unas semanas, y está bien.',
    practica:'Proponer un plan para dos a una amiga o un amigo' }
]};

/* ---------- «Para ti»: eliges lo que va contigo (se guarda solo en tu móvil) ---------- */
const PERFIL = [
  { id:'ansiedad', n:'La ansiedad social me frena mucho', consejos:[
    'Empieza por los sitios más fáciles (actividades que se repiten, intercambios de idiomas) antes que discotecas.', 'Usa «Tengo un plan» antes de cada salida: decidir de antemano cuánto rato te quedas quita muchísimo miedo.', 'Mide el miedo antes y después. Con el tiempo verás que lo de antes casi siempre es peor.', 'Un poco cada semana vale más que mucho una vez. La constancia es lo que cambia la ansiedad.' ] },
  { id:'espectro', n:'Tengo rasgos del espectro o me cuesta leer lo implícito', consejos:[
    'Usa la chuleta de frases: tener frases preparadas no es hacer trampa, es usar una herramienta.', 'Cuando no sepas si le gustas o si quiere seguir hablando, pregunta con palabras. La claridad es tu mejor aliada y mucha gente la agradece.', 'Las señales de «¿Le gusto?» están escritas en forma de lista para que no tengas que adivinarlas.', 'Elige sitios con menos ruido y luz suave si te saturan: cafés, paseos, terrazas tranquilas. La primera cita no tiene que ser en un bar lleno.', 'Si mirar a los ojos te cansa, mira a la cara en general y asiente. No te fuerces.', 'Hablar mucho de un tema que te apasiona es bonito. Para que sea conversación, pregunta de vez en cuando: «¿A ti te gusta algo de esto?».', 'Planifica descansos después de planes sociales: no es debilidad, es cómo recargas.' ] },
  { id:'cero', n:'Parto de cero', consejos:[
    'No tienes que recuperar el tiempo perdido. Cada persona tiene su ritmo y nadie te va a pedir un historial.', 'Si en una cita sale el tema, la verdad sencilla basta: «No he tenido muchas relaciones». Sin justificarte.', 'Practica primero conversaciones sin nada en juego: compañeros, vecinos, gente de actividades. Es el mismo músculo.', 'Lo físico, cuando llegue, a tu ritmo. Preguntar y decir «vamos despacio» es perfectamente normal.' ] },
  { id:'autoestima', n:'Me cuesta verme con valor', consejos:[
    'Rellena «Conócete»: tus valores, puntos fuertes y las tres palabras que te digan tus amigos. Léelo antes de un plan.', 'Cada noche, tres cosas que hiciste bien. Parece tonto y funciona.', 'Que alguien no se interese por ti no confirma lo que piensas de ti. Es una persona concreta en un momento concreto.', 'Lleva a terapia los pensamientos que más se repiten. Para eso está «Para la próxima sesión».' ] },
  { id:'introvertido', n:'Me cansa mucho la gente y necesito recargar', consejos:[
    'Planes cortos y para dos o pocos, mejor que fiestas largas.', 'Ponte una hora de salida antes de ir y respétala sin culpa.', 'Las primeras citas de día (café, paseo) cansan menos que las de noche.', 'No tienes que estar siempre disponible: encajarás mejor con gente que también valora la calma.' ] },
  { id:'terapia', n:'Voy a terapia', consejos:[
    'Lleva a sesión lo que pase en los retos y en los planes: es justo el material con el que se trabaja.', 'Comparte con tu terapeuta los apartados de esta app que te remuevan.', 'No hace falta contarle a una cita que vas a terapia hasta que haya confianza, y cuando lo cuentes, puedes hacerlo con naturalidad.' ] },
  { id:'medicacion', n:'Tomo medicación para la ansiedad o el ánimo', consejos:[
    'Con el alcohol, cuidado: pregunta a tu médico cuánto es razonable con tu medicación.', 'Si notas cambios en el deseo o en la erección, coméntalo con tu médico: es frecuente y suele tener solución. No la dejes por tu cuenta.', 'Tomar medicación es cuidarte. No es algo que tengas que explicar a nadie.' ] },
  { id:'oficina', n:'Trabajo en horario de oficina', consejos:[
    'Las tardes entre semana sirven para actividades que se repiten (un curso, un club). Ahí es donde más gente se conoce.', 'Los viernes por la tarde y los findes, para planes y citas.', 'En el trabajo, mucho cuidado con quién te gusta (mira «En el trabajo» en la guía).' ] },
  { id:'musica', n:'Me gusta mucho la música', consejos:[
    'Conciertos pequeños y salas: es fácil comentar con quien tienes al lado.', 'La música es un tema de conversación muy fácil: «¿Qué estás escuchando últimamente?».', 'Pasar una canción o una lista a alguien es una excusa natural para escribirle.', 'Clases de baile o de un instrumento: actividad que se repite y con gente.' ] },
  { id:'futbol', n:'Me gusta el fútbol', consejos:[
    'Ver partidos en un bar con gente es fácil: hay tema de conversación garantizado.', 'Si a ella no le interesa, no lo conviertas en tu único tema: pregunta qué le gusta a ella.', 'Fútbol 7 o pachangas con gente nueva: una forma de hacer amigos, que traen amigas.' ] },
  { id:'gym', n:'Hago ejercicio o voy al gimnasio', consejos:[
    'Clases dirigidas, clubs de correr o escalada: hay más trato que entrenando solo.', 'El ejercicio baja la ansiedad. Ir antes de un plan puede ayudarte.', 'En la sala, respeto ante todo: mira «En el gimnasio» en la guía.' ] },
  { id:'cocina', n:'Me gusta cocinar', consejos:[
    'Cursos de cocina: muy sociales y se habla mientras se hace algo.', 'Recomendar un plato o un sitio de comida es un tema fácil y cercano.', 'Más adelante, cocinar para alguien es un plan muy bonito (no para la primera cita).' ] },
  { id:'series', n:'Me gustan las series, pelis o los libros', consejos:[
    '«¿Qué estás viendo o leyendo ahora?» es de las mejores preguntas para empezar.', 'Clubes de lectura y cinefórums: gente con ganas de hablar.', 'Un plan de cine, con algo después para comentar la peli.' ] },
  { id:'videojuegos', n:'Me gustan los videojuegos o los juegos de mesa', consejos:[
    'Bares y quedadas de juegos de mesa: se habla mientras se juega, sin silencios incómodos.', 'Es un tema que mucha gente comparte, más de lo que crees.' ] },
  { id:'viajar', n:'Me gusta viajar o salir a la montaña', consejos:[
    'Grupos de senderismo de fin de semana: muy fáciles para conocer gente.', '«¿Cuál es el mejor sitio en el que has estado?» casi siempre abre una buena conversación.' ] }
];
GUIA.push(GUIA_EXTRA);
