/* Contenido ampliado 2: carisma, confianza, señales, trucos, preguntas, cambios de etapa y muchas más situaciones.
   Todo genérico. Nada de esto sirve para manipular: sirve para estar más tranquilo y tratar mejor a la gente. */
'use strict';

DOCS.push(
  { id:'d-carisma', grupo:'carisma', icono:'✨', titulo:'Carisma: qué es y cómo se entrena', sub:'No es un don: son tres cosas que se practican', secciones:[
    ['Qué es de verdad', ['El carisma no es ser el más gracioso ni el centro de atención. Es cómo se siente la gente cuando está contigo.', 'Se suele explicar con tres piezas: presencia (estar de verdad con la persona), calidez (que note que te cae bien y te importa) y seguridad (que se te vea tranquilo con quien eres).', 'Las tres se entrenan. Mucha gente carismática era tímida y aprendió.']],
    ['Presencia', ['Cuando hables con alguien, deja el móvil y la cabeza en otro sitio: escucha como si fuera lo único que hay.', 'Si te pillas pensando qué vas a decir o cómo te ven, vuelve a lo que te está contando. Es lo que más se nota.', 'Pregunta por lo que acaba de decir, no por lo que llevabas preparado.']],
    ['Calidez', ['Sonríe al ver a la gente, sobre todo al principio y al despedirte.', 'Alégrate de verla y díselo: «¡Qué bien verte!».', 'Recuerda cosas suyas y pregunta por ellas otro día.', 'Interésate sin juzgar. La gente vuelve a quien la hace sentir bien.']],
    ['Seguridad', ['Habla un poco más despacio y deja pausas: la prisa transmite nervios.', 'Ocupa tu espacio: hombros sueltos, espalda recta sin rigidez, sin encogerte.', 'No pidas perdón por todo ni te justifiques de más.', 'Di lo que piensas y lo que quieres con calma: «Me apetece ir a…», «Prefiero…».', 'Seguridad no es no tener miedo: es hacer las cosas aunque lo tengas.']],
    ['Lo que lo estropea', ['Hablar solo de ti o intentar impresionar.', 'Estar pendiente del móvil.', 'Quejarse mucho o hablar mal de otros.', 'Buscar aprobación todo el rato («¿verdad?», «¿te parece bien?» a cada frase).']],
    ['Ejercicio para esta semana', ['En cada conversación, haz una cosa: mirar y escuchar de verdad, alegrarte de ver a alguien o decir una opinión tuya con calma. Una sola. Al final de la semana, apunta en el diario cuál te costó menos.']]
  ]},
  { id:'d-confianza', grupo:'carisma', icono:'🦁', titulo:'Confianza en ti mismo', sub:'De dónde sale y cómo hacer que no dependa de los demás', secciones:[
    ['De dónde sale la confianza', ['De dos cosas: de haber hecho algo muchas veces (experiencia) y de tratarte bien aunque salga mal (aceptación).', 'La primera se gana con práctica: cada reto suma. La segunda se gana hablándote como a un amigo.', 'No se consigue esperando a sentirte seguro. Se consigue actuando aunque no lo estés.']],
    ['Confianza que no depende de nadie', ['Si tu valor depende de que alguien te diga que sí, cada «no» te hunde. Si depende de lo que tú haces (intentarlo, tratar bien a la gente, cuidarte), nadie te lo puede quitar.', 'Ponte objetivos que dependan de ti: «hoy saludo primero», no «hoy le gusto».', 'Celebra el intento, no el resultado.']],
    ['Cosas que hacen subir la confianza', ['Cumplir lo que te prometes, aunque sea pequeño: hacer ejercicio, levantarte a la hora, escribir ese mensaje.', 'Cuidar tu aspecto a tu manera: ropa que te guste y te quede bien, pelo y barba arreglados.', 'Hacer cosas que se te dan bien y estar con gente que te valora.', 'Tener tu vida: aficiones, planes, proyectos. Te da temas y te quita presión.', 'Ir anotando lo que consigues. La memoria olvida los logros y recuerda los fallos.']],
    ['Cuando vuelve la inseguridad', ['Es normal que vuelva en momentos de cambio, cansancio o tras un «no». No significa que hayas vuelto al principio.', 'Mira tu Recorrido: ahí están los datos de lo que ya has hecho.', 'Haz un reto pequeño de las primeras etapas. Recupera la sensación de «puedo».', 'Llévalo a terapia: es exactamente para eso.']]
  ]},
  { id:'d-delante', grupo:'carisma', icono:'🙋', titulo:'Cómo actuar delante de una chica', sub:'Los principios que valen para cualquier momento', secciones:[
    ['La idea base', ['Trátala como a una persona interesante, no como a un examen ni a un premio. Con eso ya haces mejor que mucha gente.']],
    ['Siempre', ['Mírala a la cara y escucha de verdad.', 'Interésate por lo que piensa, no solo por lo que hace.', 'Sé tú: tus gustos, tu humor, tus opiniones. Mejor gustar a quien encaja contigo que fingir para gustar a cualquiera.', 'Mantén el respeto: nada de comentarios sobre su cuerpo al principio, nada de presionar.', 'Deja que también hable ella. Una buena conversación es un ping-pong.']],
    ['Lo que funciona muy bien', ['El humor ligero y la complicidad: reíros de algo juntos.', 'Mostrar intención con claridad cuando llega el momento: «Me gustas», «Me apetece volver a verte». La claridad atrae más que los rodeos.', 'Proponer tú los planes, sin imponer: «¿Te apetece ir a…?».', 'Tener tu vida y tus planes: no depender de que ella te conteste para estar bien.']],
    ['Lo que resta', ['Adular demasiado o ponerla en un pedestal.', 'Estar siempre disponible y de acuerdo con todo.', 'Desaparecer o hacerse el interesante a propósito.', 'Insistir cuando no hay interés.', 'Hablar mal de otras chicas o de tus ex.']],
    ['Si te pones nervioso delante de ella', ['Respira soltando aire largo y pon la atención en lo que dice.', 'Si se nota, dilo con humor: «Perdona, me pones un poco nervioso». Muchas veces gusta.', 'No hace falta llenar todos los silencios.']]
  ]},
  { id:'d-senales', grupo:'ligar', icono:'👁️', titulo:'Señales del cuerpo: qué pueden significar', sub:'Pistas, no pruebas: cómo leerlas sin equivocarte', secciones:[
    ['Antes de nada', ['Ninguna señal sola demuestra nada. Lo que cuenta es que haya varias a la vez y que se repitan.', 'El contexto cambia todo: frío, cansancio, timidez o ser una persona muy expresiva.', 'Para saber algo de verdad, hace falta preguntar o dar un paso. Para algo físico, solo vale un sí claro con palabras.']],
    ['Señales que suelen indicar interés', ['Te mira, aparta la vista y vuelve a mirarte, varias veces.', 'Se gira hacia ti con el cuerpo y los pies, no solo la cara.', 'Se acerca o no se aparta cuando estáis cerca.', 'Se ríe mucho con lo que dices, aunque no sea tan gracioso.', 'Te toca el brazo o el hombro al hablar.', 'Se toca el pelo o se recoloca la ropa al verte (se arregla para ti).', 'Imita sin darse cuenta tus gestos o tu postura.', 'Las pupilas se dilatan cuando algo nos interesa, aunque también por la luz. Es muy difícil verlo y no hay que fiarse de esto.', 'Busca excusas para alargar la conversación o volver a verte.', 'Te escribe ella también, con preguntas.']],
    ['Señales de que está a gusto (no necesariamente interés)', ['Sonríe, te cuenta cosas suyas, se relaja.', 'Contesta con ganas y te sigue la broma.', 'Ser simpática no es lo mismo que estar interesada: fíjate en si te busca a ti en concreto.']],
    ['Señales de incomodidad o de querer irse', ['Brazos cruzados junto con el cuerpo girado hacia otro lado.', 'Pies apuntando a la salida o a otra persona.', 'Mira el móvil o alrededor a menudo.', 'Respuestas cortas, sonrisa cerrada (sin enseñar los dientes) y sin preguntas.', 'Se echa hacia atrás cuando te acercas.', 'Ante estas, cierra con amabilidad: «Bueno, te dejo. ¡Me ha gustado hablar contigo!».']],
    ['Mitos', ['«Si se toca el pelo, le gustas»: a veces sí, a veces tiene el pelo en la cara.', '«Si cruza los brazos, te rechaza»: o tiene frío, o está cómoda así.', '«Si es borde, es que le gustas»: no. Si es borde, es borde.', '«Las chicas dicen no cuando quieren decir sí»: falso y peligroso. No es no.']]
  ]},
  { id:'d-trucos2', grupo:'carisma', icono:'🧩', titulo:'Más trucos psicológicos', sub:'Para conversar, caer bien y sentirte mejor', secciones:[
    ['Para caer bien', ['Efecto del error: tener un pequeño fallo (un tropiezo, reírte de ti) hace a la gente más cercana, sobre todo si por lo demás vas bien.', 'Contar algo personal, poco a poco, hace que la otra persona también se abra. Se avanza por turnos.', 'La gente recuerda cómo la hiciste sentir más que lo que dijiste.', 'Un cumplido concreto vale mucho más que uno general: «Me encanta cómo te ríes» mejor que «eres muy guapa».', 'Repetir de vez en cuando las últimas palabras de la otra persona en tono de pregunta («¿Te fuiste sola a Japón?») hace que siga contando.', 'Coincidir en algo, aunque sea pequeño, acerca muchísimo. Busca los «yo también» sinceros.', 'Verse a menudo aumenta el aprecio por sí solo: la familiaridad gusta.']],
    ['Para que la conversación sea mejor', ['En vez de preguntar, a veces afirma algo y deja que te corrija: «Pareces de las que madrugan». Es más divertido que un interrogatorio.', 'Las bromas que vuelven: recuerda algo gracioso de antes y sácalo más tarde. Crea complicidad.', 'Cuenta historias con estructura: cómo empezó, qué salió mal y cómo acabó. Mejor cortas.', 'Pregunta por emociones, no solo por datos: «¿Y qué es lo que más te gusta de tu trabajo?» en vez de «¿De qué trabajas?».', 'Deja frases abiertas que inviten a seguir: «Lo de la semana pasada fue una locura…».', 'Si hay un silencio, sonríe y espera un segundo: muchas veces la otra persona lo llena.']],
    ['Para coquetear con respeto', ['Bromear con complicidad, nunca para hacerla sentir mal.', 'Retos ligeros: «A que no te atreves a probar el picante».', 'Hablar del «nosotros» en broma: «Seríamos un desastre haciendo un mueble de Ikea juntos».', 'Mantener un poco más la mirada y sonreír.', 'Decir lo que te gusta de forma directa y sin presión: «Me lo estoy pasando muy bien contigo».', 'Lo que no: el «negging» (meterse con ella para bajarle la autoestima). Es manipulación y además funciona fatal.']],
    ['Para tu cabeza', ['Toma distancia de los pensamientos: «Estoy teniendo el pensamiento de que me va a salir mal». Les quita fuerza.', 'Ponte objetivos de proceso, no de resultado: «hacer tres preguntas» en vez de «que le guste».', 'Los tres intentos: antes de decidir que algo no va contigo, inténtalo tres veces.', 'El rechazo es información, no un juicio: te dice algo de esa situación, no de lo que vales.', 'Imagina la escena saliendo bien antes de hacerlo, con detalle. Prepara al cerebro.', 'La postura abierta te hace sentir algo más seguro (lo de que cambia las hormonas no se ha confirmado, pero sentirte mejor sí).', 'Modo curioso: entra en cada conversación pensando «¿qué tendrá de interesante esta persona?». Quita presión y te hace mejor conversador.']],
    ['Cosas que te darás cuenta si las pruebas', ['Si saludas a alguien por su nombre, verás que te sonríe más.', 'Si escuchas más de lo que hablas, verás que la gente dice que eres buen conversador.', 'Si propones un plan concreto, verás que te dicen que sí más a menudo que con «a ver si quedamos».', 'Si te despides en un buen momento, verás que la gente tiene ganas de volver a verte.', 'Si dices «estoy nervioso», verás que casi nadie se lo toma mal.']]
  ]},
  { id:'d-preguntas', grupo:'ligar', icono:'❓', titulo:'Preguntas buenas para conocer a alguien', sub:'Para cuando no sabes qué preguntar en una cita', secciones:[
    ['Para empezar', ['¿Qué tal la semana? ¿Algo bueno?', '¿Cómo acabaste viviendo en Barcelona?', '¿Cuál es tu barrio favorito y por qué?', '¿Qué haces cuando tienes un día libre de verdad?', '¿Qué estás viendo, leyendo o escuchando últimamente?']],
    ['Para ir un poco más allá', ['¿Qué es lo que más te gusta de lo que haces?', 'Si pudieras dedicarte a cualquier cosa, ¿qué harías?', '¿Cuál es el mejor viaje que has hecho?', '¿Qué te hacía ilusión de pequeña?', '¿Hay algo que siempre has querido aprender?', '¿Cuál es tu plan perfecto de domingo?']],
    ['Divertidas', ['¿Cuál es tu comida de «día malo»?', 'Si tuvieras que comer lo mismo toda la vida, ¿qué sería?', '¿Qué canción te sabes entera aunque te dé vergüenza?', '¿Playa o montaña? Y no vale decir las dos.', '¿Cuál es la peor peli que has visto y te gustó?', '¿Qué es lo más raro que has comido?']],
    ['Cuando ya hay confianza', ['¿Qué es lo que más valoras en tus amigos?', '¿Hay algo de lo que estés orgullosa últimamente?', '¿Qué te hace reír siempre?', '¿Cómo sería para ti un buen año?']],
    ['Cómo usarlas', ['No es un cuestionario: haz una, escucha, pregunta más sobre su respuesta y cuenta tú la tuya.', 'Las mejores preguntas salen de lo que acaba de decir.']]
  ]},
  { id:'d-cambio', grupo:'yo', icono:'🔄', titulo:'Si cambias de trabajo o de etapa', sub:'Para no perder lo que has avanzado', secciones:[
    ['Lo que no se pierde', ['Lo que has aprendido socializando se queda: está en ti, no en tu trabajo actual.', 'Puede que al principio vuelva algo de ansiedad: es normal en cualquier cambio, incluso para gente sin ansiedad social. Suele bajar en unas semanas.', 'Que vuelvan los nervios no significa que vuelvas al principio. Significa que estás en un sitio nuevo.']],
    ['Antes del cambio', ['Escribe en Conócete lo que ya has conseguido este año. Léelo el primer día.', 'Prepara tres frases para presentarte: «Hola, soy ___, acabo de entrar en ___. ¿Tú cuánto llevas aquí?».', 'Habla del cambio en terapia antes de que pase.']],
    ['Las primeras semanas', ['Objetivo pequeño cada día: saludar a dos personas, comer una vez con compañeros, hacer una pregunta.', 'Apúntate a lo que surja (cafés, comidas, afterworks), aunque sea un rato.', 'Recuerda nombres y algo de cada persona.', 'No hace falta caer bien a todo el mundo el primer mes: la confianza se hace con el tiempo.', 'Si una semana cuesta más, vuelve a los retos de las primeras etapas: recuerdan al cuerpo que puede.']],
    ['Si notas que vuelve la baja autoestima', ['Mira tu Recorrido y tu diario: los datos no mienten.', 'Escribe un pensamiento en «Revisar un pensamiento».', 'Trátate como a un amigo que empieza en un trabajo nuevo: con paciencia.', 'Cuéntalo en terapia. Prevenir es mucho más fácil que remontar.']]
  ]}
);

/* ---------- Muchas más situaciones ---------- */
const S_ = (id, titulo, pasa, hacer, sale, practica, extra) => ({ id, titulo, pasa, hacer, ejemplos: [], cierre: '', extra: extra || [], sale, practica });
GUIA.push(
  { bloque:'Con ella delante', items:[
    S_('g-mira', 'Te mira y sonríe desde lejos', 'Cruzáis miradas y ella sonríe. No sabes qué hacer y miras al suelo.', ['Devuelve la sonrisa, aguanta la mirada un segundo y sigue con lo tuyo. Ya es mucho.', 'Si vuelve a pasar y hay ocasión, acércate con algo sencillo: «Hola, te he visto antes y me apetecía saludarte».', 'Una sonrisa no es una invitación a todo: es solo una sonrisa amable. Si te acercas y no sigue la conversación, no pasa nada.'], 'Si te quedaste mirando al suelo, la próxima vez. Esto se entrena.', 'Devolver una sonrisa a alguien, sin apartar la mirada'),
    S_('g-pillada', 'Te pilla mirándola', 'Te das cuenta de que te ha visto mirándola y te mueres de vergüenza.', ['Sonríe en vez de apartar la mirada de golpe. Convierte un momento raro en uno amable.', 'No te quedes mirando fijamente después. Una vez y sonrisa.'], 'Si apartaste la mirada corriendo, no lo recordará. Pasa a todo el mundo.', 'Sonreír si alguien me pilla mirando'),
    S_('g-solos', 'Os quedáis a solas un momento', 'En el ascensor, en la cocina del trabajo o esperando a alguien. El silencio pesa.', ['Una frase sobre el momento: «Qué día más largo», «¿Tú también esperas a ___?».', 'Si te contesta con ganas, una pregunta más. Si no, una sonrisa basta.'], 'Si no dijiste nada, no pasa nada: es un momento muy corto.', 'Decir una frase en un ascensor o en una espera'),
    S_('g-toca', 'Te toca el brazo al hablar', 'Te ha tocado el brazo un momento y no sabes si significa algo.', ['Suele ser una buena señal de confianza o de interés, sobre todo si se repite.', 'No hace falta reaccionar de forma especial: sonríe y sigue. Puedes devolver un toque ligero en el brazo más adelante, si es natural.', 'Que te toque no da permiso para nada más. El siguiente paso, con calma y fijándote en cómo responde.'], 'Si no supiste qué hacer, no pasa nada: no hacer nada raro ya está bien.', 'Fijarme en cómo me siento cuando alguien es cercano conmigo'),
    S_('g-amigas', 'Te presenta a sus amigas', 'Vas a conocer a su grupo y te da miedo no estar a la altura.', ['Es buena señal: te quiere en su vida.', 'Saluda a cada una por su nombre y pregúntales cosas a ellas, no solo hables con ella.', 'No hace falta brillar: con ser amable y escuchar, ya caes bien.'], 'Si estuviste más callado, no pasa nada. Lo que se recuerda es si fuiste amable.', 'Preguntar algo a cada persona nueva de un grupo'),
    S_('g-otro', 'Hay otro chico interesado en ella', 'Ves que otro también le habla y te desanimas o te pones celoso.', ['No es una competición: ella elige. Tú sigue siendo tú y mostrando interés con claridad.', 'No hables mal del otro ni intentes «ganarle».', 'Si ella elige al otro, se respeta. Y no dice nada de lo que vales.'], 'Duele, y es normal. Llévalo al diario.', 'Hacer algo por mí cuando me compare con otros'),
    S_('g-calle', 'Te la encuentras por la calle', 'Ves de repente a alguien que te gusta y te bloqueas.', ['Saluda con una sonrisa: «¡Hola! ¿Qué haces por aquí?».', 'Si tiene prisa, «¡Me alegro de verte!» y sigues. Si no, un par de frases.', 'Un encuentro corto y simpático deja muy buen recuerdo.'], 'Si no la saludaste por los nervios, la próxima vez será más fácil.', 'Saludar a alguien conocido que me encuentre por la calle')
  ]},
  { bloque:'En la cita', items:[
    S_('g-silencio', 'Un silencio incómodo en la cita', 'Se acaba un tema y no sabes qué decir. Sientes que todo va mal.', ['Vuelve a algo que dijo antes o usa una de las «Preguntas buenas».', 'Comenta algo del sitio: la música, la comida, la gente.', 'O dilo con humor: «Me he quedado en blanco. ¿Qué me estabas contando de…?».', 'Un silencio corto es normal incluso en citas que van genial.'], 'Si hubo varios silencios, no significa que fuera mal. Fíjate en si quiere repetir.', 'Llevar pensadas tres preguntas a la próxima cita'),
    S_('g-experiencia', 'Te pregunta por tu experiencia o tus ex', 'Te pregunta por relaciones anteriores y te da vergüenza no tener mucho que contar.', ['La verdad sencilla basta: «No he tenido muchas relaciones, la verdad. ¿Y tú?».', 'No te justifiques ni des explicaciones largas: no es un examen.', 'Si ella cuenta de su ex, escucha sin juzgar y no te compares.'], 'Si te salió algo torpe, lo más probable es que ni se acuerde.', 'Ensayar en voz alta mi respuesta sencilla'),
    S_('g-trabajo-verguenza', 'Te pregunta a qué te dedicas y no te gusta tu respuesta', 'Te da vergüenza tu trabajo o sientes que no es interesante.', ['Cuenta lo que haces y algo que te guste de ello, o lo que te gustaría hacer.', 'Rápido y con naturalidad, y devuelve la pregunta.', 'A casi nadie le importa tanto tu trabajo como a ti. Le importa cómo hablas de tu vida.'], 'Nadie juzga tanto como imaginas.', 'Preparar una forma corta y positiva de contar a qué me dedico'),
    S_('g-cuenta', 'Llega la cuenta', 'No sabes si pagar tú, pagar a medias o qué.', ['Lo más sencillo: «¿Lo pagamos a medias?» o «Esta la pago yo y la próxima tú».', 'Si ella insiste en pagar su parte, acéptalo sin más.', 'No es una prueba de nada.'], 'Cualquier opción amable está bien.', 'Pensar antes de la cita qué voy a proponer al pagar'),
    S_('g-beso', 'El primer beso: cómo saber el momento', 'Sientes que podría pasar pero te da miedo equivocarte.', ['Señales de que puede ser buen momento: estáis cerca, se queda mirándote, sonríe, no se aparta, la cita ha ido bien.', 'Lo más seguro y respetuoso es preguntar: «¿Te puedo dar un beso?». Solo vale un sí claro.', 'Si duda o dice que no: «Vale, sin problema», con una sonrisa, y sigue normal.', 'No hace falta que pase en la primera cita.'], 'Si el beso es torpe, ríete: casi todos los primeros besos lo son.', 'Recordarme que preguntar es lo correcto'),
    S_('g-casa', 'Te propone ir a su casa o «la última»', 'La cita va bien y te propone seguir en su casa o tomar algo más.', ['Puedes decir que sí si te apetece, o que no si no te sientes preparado: «Me lo he pasado genial. Hoy prefiero irme, pero quiero repetir».', 'Ir a su casa no obliga a nada, ni a ti ni a ella. Cada paso se pregunta y se puede parar.', 'Si estás nervioso, puedes decirlo. Ir despacio está bien.'], 'Elijas lo que elijas, si lo haces con respeto, está bien.', 'Pensar qué quiero yo antes de la cita'),
    S_('g-cierre', 'La cita va muy bien: cómo cerrarla', 'Te lo estás pasando genial y no sabes cómo terminar sin estropearlo.', ['Termina en un buen momento, no cuando ya no hay nada que decir.', 'Dilo claro: «Me lo he pasado muy bien. Me apetece mucho repetir».', 'Despídete con un abrazo, un beso si ya ha habido, o dos besos.', 'Escríbele esa noche o al día siguiente.'], 'Si la despedida fue rara, el mensaje del día siguiente lo arregla.', 'Decir en voz alta a alguien que me lo he pasado bien'),
    S_('g-bloqueo', 'Te bloqueas por los nervios en plena cita', 'De repente notas mucha ansiedad, la cabeza en blanco y ganas de irte.', ['Ve un momento al baño: respira soltando el aire largo cinco veces.', 'Vuelve y pregunta algo sencillo sobre ella.', 'Si estás muy mal, puedes irte con amabilidad: «Perdona, no me encuentro muy bien. Me lo estaba pasando bien, ¿lo repetimos otro día?».'], 'Esto le pasa a mucha gente. No es un fracaso: aguantar ya es un logro.', 'Usar «Un momento difícil» antes de una cita'),
    S_('g-sin-chispa', 'En persona no hay chispa', 'Por la app te gustaba mucho, pero en persona no sientes nada.', ['Pasa muy a menudo y no es culpa de nadie.', 'Termina la cita con amabilidad y, si te escribe, sé claro: «Me lo pasé bien, pero no siento que vaya a más».'], 'No es tiempo perdido: es práctica y una persona más a la que has conocido.', 'Ser claro con amabilidad cuando algo no me encaja')
  ]},
  { bloque:'Mensajes y apps', items:[
    S_('g-visto', 'Te deja en visto', 'Has escrito y ves que lo ha leído pero no contesta.', ['Puede estar ocupada y contestar luego. No escribas otra vez enseguida.', 'Si pasan unos días, un mensaje ligero y no insistas más: «¡Hola! ¿Qué tal la semana?».', 'Si sigue sin contestar, dalo por cerrado sin reproches.'], 'No dice nada de ti: dice que ahora no es para ella.', 'Esperar sin escribir dos veces seguidas'),
    S_('g-ella-escribe', 'Ella te escribe primero', 'Te escribe ella y no sabes qué contestar para no estropearlo.', ['¡Buena señal! Contesta con ganas y pregunta algo.', 'Si lleváis un rato a gusto, propón veros.'], 'Cualquier respuesta amable está bien.', 'Contestar con una pregunta para seguir la conversación'),
    S_('g-cancela', 'Te cancela la cita', 'Te dice que no puede el día que habíais quedado.', ['Si propone otro día, es buena señal: acéptalo.', 'Si no propone nada, pregunta una vez: «¡Sin problema! ¿Te va bien otro día?».', 'Si vuelve a pasar sin proponer, déjalo estar.'], 'Las cancelaciones pasan. No es personal.', 'Responder con calma a un cambio de planes'),
    S_('g-nada-serio', 'Te dice que no busca nada serio', 'Te dice claramente que no busca una relación.', ['Agradece la sinceridad.', 'Piensa qué quieres tú. Si buscas algo más, mejor decirlo y no seguir para no hacerte daño.', 'Si a ti también te encaja, sed claros los dos y con respeto.'], 'Saber lo que quiere cada uno os ahorra problemas a los dos.', 'Saber qué busco yo antes de conocer a alguien'),
    S_('g-amigo', 'Te dice que te ve como amigo', 'Te dice que le caes muy bien pero que no siente algo más.', ['Respuesta: «Vale, gracias por decírmelo».', 'Decide si puedes ser su amigo sin esperar nada. Si no, tomar distancia está bien.', 'No intentes «convencerla».'], 'Duele. Que te vea como amigo significa que te valora, solo que no de esa forma.', 'Apuntar en el diario cómo me siento después')
  ]},
  { bloque:'Tu vida social', items:[
    S_('g-nadie', 'Llegas a una fiesta y no conoces a nadie', 'Entras, no ves caras conocidas y te dan ganas de irte.', ['Busca a quien te invitó y salúdale primero.', 'Acércate a la zona de bebida o comida: es donde más fácil se habla.', 'Busca a alguien que esté solo: suele agradecer que le hablen.', 'Ponte un mínimo de tiempo (una hora) antes de decidir si te vas.'], 'Si te quedaste poco, ir ya es la victoria.', 'Quedarme mi tiempo mínimo en un plan'),
    S_('g-afterwork', 'Comida de empresa o afterwork', 'Hay que socializar con compañeros fuera del trabajo y te da pereza o miedo.', ['Ve aunque sea un rato: se nota y se valora.', 'Siéntate al lado de alguien con quien ya hablas y amplía desde ahí.', 'Habla de cosas que no sean trabajo: planes, series, vacaciones.', 'Con el alcohol, con calma.'], 'Una comida regular no cambia lo que piensan de ti en el trabajo.', 'Ir a la próxima comida o afterwork'),
    S_('g-primer-dia', 'Tu primer día en un trabajo nuevo', 'Todo es nuevo y vuelve la ansiedad de golpe.', ['Preséntate con una frase preparada: «Hola, soy ___, acabo de entrar. ¿Tú cuánto llevas aquí?».', 'Apunta nombres y algo de cada persona.', 'Pregunta cosas: a la gente le gusta ayudar a quien llega.', 'Acepta la primera invitación a café o comida.', 'Mira «Si cambias de trabajo o de etapa» en Conócete.'], 'Es normal salir agotado el primer día. Descansa sin culpa.', 'Preparar mi frase de presentación'),
    S_('g-consejo', 'Te pide ayuda o un consejo', 'Una chica te pide ayuda con algo o tu opinión.', ['Ayuda de verdad si puedes. Es una buena forma de conectar.', 'No lo conviertas en una oportunidad de impresionar: escucha qué necesita.', 'Si sale bien, puedes proponer algo después: «¿Te invito a un café por haberte salvado la tarde?», en broma.'], 'Ayudar sin esperar nada ya habla bien de ti.', 'Ofrecer ayuda a alguien esta semana')
  ]}
);

/* Más consejos en «Para ti» */
PERFIL.push(
  { id:'mejorando', n:'Ya socializo mejor, pero ligar me cuesta mucho', consejos:[
    'Lo que has avanzado socializando es la base de ligar: es el mismo músculo con más en juego. No empiezas de cero.', 'Ve subiendo poco a poco: primero, conversaciones con chicas sin intención (como con cualquiera); luego, mostrar un poco de interés; luego, un plan.', 'Usa las etapas 3, 4 y 5 de los retos: están pensadas justo para este salto.', 'Mide el miedo antes y después en cada intento. Verás que baja igual que bajó al socializar.', 'Dale tiempo: socializar te ha costado un año y lo has conseguido. Esto también.' ] },
  { id:'cambio', n:'Me preocupa volver atrás si cambio de trabajo', consejos:[
    'Lo que has aprendido se queda contigo, no en tu trabajo.', 'Es normal que vuelvan algo los nervios al principio. Suele bajar en unas semanas.', 'Lee «Si cambias de trabajo o de etapa» en Conócete antes del cambio.', 'Escribe en «Carta para ti» todo lo que has conseguido para leerlo el primer día.' ] }
);
